
const USER = {
    UPDATE_USER : "UPDATE_USER",
    UPDATE_FACET : "UPDATE_CURRENT_FACET",
    UPDATE_SEARCH_SET : "UPDATE_SEARCH_SET",
    UPDATE_SEARCH_SET_VERTICAL : "UPDATE_SEARCH_SET_VERTICAL",
    HIDE_REGISTRATION_BANNER: 'HIDE_REGISTRATION_BANNER',
    INCREMENT_REGISTRATION_STEP: 'INCREMENT_REGISTRATION_STEP',
};
const PREVIEW={
    UPDATE_ITEM_PREVIEW : "UPDATE_ITEM_PREVIEW"
};

const SEARCH={
    UPDATE_FILTER:"UPDATE_FILTER",
    UPDATE_LOADING : "UPDATE_LOADING",
    UPDATE_SEARCH_PARAMS:"UPDATE_SEARCH_PARAMS"
};
const LUIS={
    UPDATE_TERM:"UPDATE_LUIS_TERM",
    UPDATE_FILTER_COURSES:"UPDATE_FILTER_COURSES",
    UPDATE_CURRENT_VERTICAL:"UPDATE_CURRENT_VERTICAL",
    CLEAN_DATA:"CLEAN_DATA"
};
export{
    USER, SEARCH, PREVIEW,LUIS
}