
const USER = {
    UPDATE_USER : "UPDATE_USER"};
const PREVIEW={
    UPDATE_ITEM_PREVIEW : "UPDATE_ITEM_PREVIEW"
};

const SEARCH={
    UPDATE_FILTER:"UPDATE_FILTER",
    UPDATE_LOADING : "UPDATE_LOADING",
    UPDATE_SEARCH_PARAMS:"UPDATE_SEARCH_PARAMS"
};
const SESSION = {
    UPDATE_FILTER: "UPDATE_FILTER",
    UPDATE_LOADING: "UPDATE_LOADING",
    UPDATE_SEARCH_PARAMS: "UPDATE_SEARCH_PARAMS"
};
export const UPDATE_GLOBAL_TERM="UPDATE_GLOBAL_TERM";
const LUIS={
    UPDATE_TERM:"UPDATE_LUIS_TERM",
    UPDATE_FILTER_COURSES:"UPDATE_FILTER_COURSES",
    UPDATE_CURRENT_VERTICAL:"UPDATE_CURRENT_VERTICAL",
    CLEAN_DATA:"CLEAN_DATA"
};
export{
    USER, SEARCH, SESSION,PREVIEW,LUIS
}