
const USER = {
    UPDATE_USER : "UPDATE_USER"};
const FLOW = {
    UPDATE_FLOW:"UPDATE_FLOW",ADD:"ADD"
};
const SEARCH={
    UPDATE_FILTER:"UPDATE_FILTER",
    UPDATE_LOADING : "UPDATE_LOADING",
    UPDATE_SEARCH_PARAMS:"UPDATE_SEARCH_PARAMS"
};
export{
    USER,FLOW,SEARCH
}