//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mobile.Views.Share.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InviteResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InviteResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mobile.Views.Share.Resources.InviteResources", typeof(InviteResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add emails separated by commas.
        /// </summary>
        public static string AddEmails {
            get {
                return ResourceManager.GetString("AddEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for spelling mistakes or try again using different keywords..
        /// </summary>
        public static string CheckFor {
            get {
                return ResourceManager.GetString("CheckFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudents friends.
        /// </summary>
        public static string CloudentsFriends {
            get {
                return ResourceManager.GetString("CloudentsFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect more accounts.
        /// </summary>
        public static string ConnectMore {
            get {
                return ResourceManager.GetString("ConnectMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your facebook account.
        /// </summary>
        public static string FbAccount {
            get {
                return ResourceManager.GetString("FbAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook friends.
        /// </summary>
        public static string FbFriends {
            get {
                return ResourceManager.GetString("FbFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find friends from.
        /// </summary>
        public static string FindFriends {
            get {
                return ResourceManager.GetString("FindFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your gmail account.
        /// </summary>
        public static string GmailAccount {
            get {
                return ResourceManager.GetString("GmailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmail friends.
        /// </summary>
        public static string GmailFriends {
            get {
                return ResourceManager.GetString("GmailFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your google plus account.
        /// </summary>
        public static string GpAccount {
            get {
                return ResourceManager.GetString("GpAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google plus friends.
        /// </summary>
        public static string GplusFriends {
            get {
                return ResourceManager.GetString("GplusFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite by email.
        /// </summary>
        public static string InviteByEmail {
            get {
                return ResourceManager.GetString("InviteByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite your friends to cloudents.
        /// </summary>
        public static string InviteFriends {
            get {
                return ResourceManager.GetString("InviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mail was sent successfully.
        /// </summary>
        public static string MailSent {
            get {
                return ResourceManager.GetString("MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your search did not
        ///produce any results..
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name.
        /// </summary>
        public static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
