//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mvc4WebRole.Controllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BoxControllerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoxControllerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mvc4WebRole.Controllers.Resources.BoxControllerResources", typeof(BoxControllerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This class already exists.
        /// </summary>
        internal static string BoxExists {
            get {
                return ResourceManager.GetString("BoxExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seems to be an issue creating this new study group.
        /// </summary>
        internal static string DashboardController_Create_Problem_with_Create_new_box {
            get {
                return ResourceManager.GetString("DashboardController_Create_Problem_with_Create_new_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload public link.
        /// </summary>
        internal static string GoogleShare {
            get {
                return ResourceManager.GetString("GoogleShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of your classmates has already posted this link.
        /// </summary>
        internal static string LinkExists {
            get {
                return ResourceManager.GetString("LinkExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link not found.
        /// </summary>
        internal static string LinkNotFound {
            get {
                return ResourceManager.GetString("LinkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documents were received.
        /// </summary>
        internal static string NoFilesReceived {
            get {
                return ResourceManager.GetString("NoFilesReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That URL doesn&apos;t seem to be valid. Please double check it and try again.
        /// </summary>
        internal static string ProblemUrl {
            get {
                return ResourceManager.GetString("ProblemUrl", resourceCulture);
            }
        }
    }
}
