//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mvc4WebRole.Controllers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SeoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mvc4WebRole.Controllers.Resources.SeoResources", typeof(SeoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Spitball - A free online and mobile social studying application built by students for students. Join the social studying revolution at Spitball!.
        /// </summary>
        internal static string AboutUsMeta {
            get {
                return ResourceManager.GetString("AboutUsMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us | Spitball.
        /// </summary>
        internal static string AboutUsTitle {
            get {
                return ResourceManager.GetString("AboutUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdvertiseWithUsMeta {
            get {
                return ResourceManager.GetString("AdvertiseWithUsMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertise with us | Spitball.
        /// </summary>
        internal static string AdvertiseWithUsTitle {
            get {
                return ResourceManager.GetString("AdvertiseWithUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AppsMeta {
            get {
                return ResourceManager.GetString("AppsMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps | Spitball.
        /// </summary>
        internal static string AppsTitle {
            get {
                return ResourceManager.GetString("AppsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BlogMeta {
            get {
                return ResourceManager.GetString("BlogMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog | Spitball.
        /// </summary>
        internal static string BlogTitle {
            get {
                return ResourceManager.GetString("BlogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study and share your class notes for {0}, online or via the Spitball app. Use Spitball for free today!.
        /// </summary>
        internal static string BoxMetaDescription {
            get {
                return ResourceManager.GetString("BoxMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string BoxTitleItems {
            get {
                return ResourceManager.GetString("BoxTitleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quizzes.
        /// </summary>
        internal static string BoxTitleQuizzes {
            get {
                return ResourceManager.GetString("BoxTitleQuizzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed the last class? Spitball got you covered! Access all of your classmates&apos; class notes anytime, anywhere. Join Spitball and open a free account today!.
        /// </summary>
        internal static string ClassNotesMeta {
            get {
                return ResourceManager.GetString("ClassNotesMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Notes | Spitball.
        /// </summary>
        internal static string ClassNotesTitle {
            get {
                return ResourceManager.GetString("ClassNotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitball.
        /// </summary>
        internal static string Cloudents {
            get {
                return ResourceManager.GetString("Cloudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Spitball&apos;s growing community! Find your course and start chatting with your friends, create study groups and share your knowledge! Open a free account today!.
        /// </summary>
        internal static string CoursesMeta {
            get {
                return ResourceManager.GetString("CoursesMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses | Spitball.
        /// </summary>
        internal static string CoursesTitle {
            get {
                return ResourceManager.GetString("CoursesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get to know Spitball - the social study platform! Get class notes, chat with your friends, create study groups and share your knowledge! Open a free account today!.
        /// </summary>
        internal static string FeaturesMeta {
            get {
                return ResourceManager.GetString("FeaturesMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features | Spitball.
        /// </summary>
        internal static string FeaturesTitle {
            get {
                return ResourceManager.GetString("FeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out all you need to know about Spitball&apos;s system. Get class notes, chat with your friends, create study groups and share your knowledge!.
        /// </summary>
        internal static string HelpMeta {
            get {
                return ResourceManager.GetString("HelpMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ | Spitball.
        /// </summary>
        internal static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Spitball&apos;s growing community of students! Get class notes, chat with your friends, create study groups and share your knowledge! Open a free account today!.
        /// </summary>
        internal static string HomePageMeta {
            get {
                return ResourceManager.GetString("HomePageMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Social Studying App | Spitball.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get class notes for free with spitball:.
        /// </summary>
        internal static string ItemMataDescription {
            get {
                return ResourceManager.GetString("ItemMataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitball is hiring! Join the social studying revolution and help Spitball build an ever growing community of students. Come and work for us!.
        /// </summary>
        internal static string JobsMeta {
            get {
                return ResourceManager.GetString("JobsMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs | Spitball.
        /// </summary>
        internal static string JobsTitle {
            get {
                return ResourceManager.GetString("JobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Spitball we take security and privacy very seriously. Your personal information is actively protected by us. Join the social studying revolution at Spitball!.
        /// </summary>
        internal static string PrivacyMeta {
            get {
                return ResourceManager.GetString("PrivacyMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy | Spitball.
        /// </summary>
        internal static string PrivacyTitle {
            get {
                return ResourceManager.GetString("PrivacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start using Spitball like a real pro! Get class notes, chat with your friends, create study groups and share your knowledge! Study anytime, anywhere with Spitball!.
        /// </summary>
        internal static string ProductMeta {
            get {
                return ResourceManager.GetString("ProductMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product - Use Spitball like a Pro | Spitball.
        /// </summary>
        internal static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See how well you are doing in {0} and test yourself with the {1} quiz your classmates have built. Start getting better grades with Spitball!.
        /// </summary>
        internal static string QuizMetaDescription {
            get {
                return ResourceManager.GetString("QuizMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        internal static string QuizTitle {
            get {
                return ResourceManager.GetString("QuizTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Spitball and join the social studying revolution! Get class notes, chat with your friends, create study groups and share your knowledge!.
        /// </summary>
        internal static string SignInMeta {
            get {
                return ResourceManager.GetString("SignInMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login | Spitball.
        /// </summary>
        internal static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to Spitball and join the social studying revolution! Get class notes, chat with your friends, create study groups and share your knowledge!.
        /// </summary>
        internal static string SignUpMeta {
            get {
                return ResourceManager.GetString("SignUpMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up | Spitball.
        /// </summary>
        internal static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out all you need to know about Spitball&apos;s terms of service. Get class notes, chat with your friends, create study groups and share your knowledge!.
        /// </summary>
        internal static string TermsMeta {
            get {
                return ResourceManager.GetString("TermsMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service | Spitball.
        /// </summary>
        internal static string TermsTitle {
            get {
                return ResourceManager.GetString("TermsTitle", resourceCulture);
            }
        }
    }
}
