//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mvc4WebRole.Views.Home.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutUsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutUsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mvc4WebRole.Views.Home.Resources.AboutUsResources", typeof(AboutUsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitball is a free online and mobile social studying application. We are a community built around academic activity so you can focus on studying. It is a place for students of any academic level to work together on assignments, find the study material they need, test their knowledge and discuss ideas.
        ///
        ///All .
        /// </summary>
        public static string DescriptionA1a {
            get {
                return ResourceManager.GetString("DescriptionA1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitball features.
        /// </summary>
        public static string DescriptionA1b {
            get {
                return ResourceManager.GetString("DescriptionA1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  are specifically designed with a student’s needs in mind, integrated as part of a single, easy to use and free social studying platform. Uploading and sharing documents with peers, taking quizzes, browsing thousands of notes from our universal database and creating new .
        /// </summary>
        public static string DescriptionA1c {
            get {
                return ResourceManager.GetString("DescriptionA1c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  as needed are all part of the freedom within our application. This freedom has allowed 250,000 students to upload .
        /// </summary>
        public static string DescriptionA1e {
            get {
                return ResourceManager.GetString("DescriptionA1e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300,000 documents.
        /// </summary>
        public static string DescriptionA1f {
            get {
                return ResourceManager.GetString("DescriptionA1f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  so far, with no barriers between them and the material they need. .
        /// </summary>
        public static string DescriptionA1g {
            get {
                return ResourceManager.GetString("DescriptionA1g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As university students, we found ourselves struggling to find a fast and efficient way to share notes and study together online. Although some schools had official services for doing just that, they were often clunky and inflexible, making it difficult for us to share ideas with students outside of our class. Social sites made it easier to meet and communicate with one another, but they were not designed for academic life (and distractions were always close at hand). To fill this gap we set out to create a  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DescriptionA2 {
            get {
                return ResourceManager.GetString("DescriptionA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Spitball?.
        /// </summary>
        public static string DescriptionQ1 {
            get {
                return ResourceManager.GetString("DescriptionQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Vision.
        /// </summary>
        public static string DescriptionQ2 {
            get {
                return ResourceManager.GetString("DescriptionQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built by students for students.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO
        ///Founder.
        /// </summary>
        public static string TeamCEO {
            get {
                return ResourceManager.GetString("TeamCEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eidan Apelbaum Ph.D..
        /// </summary>
        public static string TeamCEOName {
            get {
                return ResourceManager.GetString("TeamCEOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTO.
        /// </summary>
        public static string TeamCTO {
            get {
                return ResourceManager.GetString("TeamCTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ram Yaari.
        /// </summary>
        public static string TeamCTOName {
            get {
                return ResourceManager.GetString("TeamCTOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design UX UI.
        /// </summary>
        public static string TeamDesigner {
            get {
                return ResourceManager.GetString("TeamDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shlomi Kastoryano.
        /// </summary>
        public static string TeamDesignerName {
            get {
                return ResourceManager.GetString("TeamDesignerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitball Team.
        /// </summary>
        public static string TeamHeader {
            get {
                return ResourceManager.GetString("TeamHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web developer.
        /// </summary>
        public static string TeamWebDev {
            get {
                return ResourceManager.GetString("TeamWebDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irena Dorfman.
        /// </summary>
        public static string TeamWebDevName {
            get {
                return ResourceManager.GetString("TeamWebDevName", resourceCulture);
            }
        }
    }
}
