//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mvc4WebRole.Views.Home.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticPagesResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticPagesResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mvc4WebRole.Views.Home.Resources.StaticPagesResources", typeof(StaticPagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Study Socially anytime and everywhere with the Spitball app. Access all of your class materials directly from your phone..
        /// </summary>
        public static string AppsSectionText1
        {
            get
            {
                return ResourceManager.GetString("AppsSectionText1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remember when your paper is due? Post a question on Spitball and get input from your peers..
        /// </summary>
        public static string AppsSectionText2
        {
            get
            {
                return ResourceManager.GetString("AppsSectionText2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find the class you&apos;ve missed or the article you&apos;ve been looking for in the library in the palm of your hand! Chat with your friends, ask questions and start studying for your next exam from any device..
        /// </summary>
        public static string AppsSectionText3
        {
            get
            {
                return ResourceManager.GetString("AppsSectionText3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find your school and start Spitballing. .
        /// </summary>
        public static string AppsSectionTitle1
        {
            get
            {
                return ResourceManager.GetString("AppsSectionTitle1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Questions about yesterday&apos;s class?.
        /// </summary>
        public static string AppsSectionTitle2
        {
            get
            {
                return ResourceManager.GetString("AppsSectionTitle2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse through thousands of class notes.
        /// </summary>
        public static string AppsSectionTitle3
        {
            get
            {
                return ResourceManager.GetString("AppsSectionTitle3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download the Spitball App!.
        /// </summary>
        public static string AppsSubtitle
        {
            get
            {
                return ResourceManager.GetString("AppsSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The simple way to share class notes, study guides, quizzes and more for FREE!.
        /// </summary>
        public static string AppsTitle
        {
            get
            {
                return ResourceManager.GetString("AppsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check out spitball&apos;s variety of class notes and articles!.
        /// </summary>
        public static string ClassNotesSubtitle
        {
            get
            {
                return ResourceManager.GetString("ClassNotesSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Class Notes.
        /// </summary>
        public static string ClassNotesTitle
        {
            get
            {
                return ResourceManager.GetString("ClassNotesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check out spitball&apos;s variety of courses!.
        /// </summary>
        public static string CoursesSubtitle
        {
            get
            {
                return ResourceManager.GetString("CoursesSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string CoursesTitle
        {
            get
            {
                return ResourceManager.GetString("CoursesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spitball can help revolutionize the way you study: Whether you’ve missed your last class and are scrambling to get class notes, have a question regarding a particularly annoying assignment, or just looking for a way to test your knowledge before your finals - Spitball has got you covered! Sign up for free, find your school and your courses and start Spitballing with your friends!.
        /// </summary>
        public static string FeaturesDescription
        {
            get
            {
                return ResourceManager.GetString("FeaturesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse through thousands of class notes to find the class you&apos;ve missed. Access all of your class material within a few clicks and upload your own class notes to help your friends excel in their upcoming papers &amp; exams. You can download the document you need to any device, print it, or check it out later, it’s not going anywhere..
        /// </summary>
        public static string FeaturesSectionText1
        {
            get
            {
                return ResourceManager.GetString("FeaturesSectionText1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to See how well you are doing and quiz yourself with one of the hundreds of quizzes that your friends have built. Build and upload your own quiz to help your fellow classmates and check your own progress. Coming up with a quiz is a great way to prepare for an exam, so gain extra Spitball points and start building quizzes..
        /// </summary>
        public static string FeaturesSectionText2
        {
            get
            {
                return ResourceManager.GetString("FeaturesSectionText2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find your course and start studying with your friends - There are more than 50,000 classes available. Couldn’t find your course? It only takes a few seconds to open a new one. Now you can invite your friends to join the course &amp; upload their material, and you will both be able to gain some sweet Spitball points..
        /// </summary>
        public static string FeaturesSectionText3
        {
            get
            {
                return ResourceManager.GetString("FeaturesSectionText3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get to know your classmates, share notes, ideas, ask questions and chat with your friends about all class related aspects. Study together and be on your way to ace your finals! Get answers directly from your classmates - they can quickly help you solve problems when your TA’s and professors are too busy..
        /// </summary>
        public static string FeaturesSectionText4
        {
            get
            {
                return ResourceManager.GetString("FeaturesSectionText4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find your school and start enjoying Spitball. New courses and class materials are uploaded everyday so you can get the most recent class material. Help build your school’s online community and get all the study materials you are looking for in one cool place. Couldn’t find your school? You can always access relevant class material from other schools, or be the first to use Spitball in your school and start the revolution!.
        /// </summary>
        public static string FeaturesSectionText5
        {
            get
            {
                return ResourceManager.GetString("FeaturesSectionText5", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Study socially anytime and everywhere with the spitball app. Access all of your class materials directly from your phone. Chat with your friends, ask questions and start studying for your next exam from any device..
        /// </summary>
        public static string FeaturesSectionText6
        {
            get
            {
                return ResourceManager.GetString("FeaturesSectionText6", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Class notes.
        /// </summary>
        public static string FeaturesSectionTitle1
        {
            get
            {
                return ResourceManager.GetString("FeaturesSectionTitle1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quizzes .
        /// </summary>
        public static string FeaturesSectionTitle2
        {
            get
            {
                return ResourceManager.GetString("FeaturesSectionTitle2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string FeaturesSectionTitle3
        {
            get
            {
                return ResourceManager.GetString("FeaturesSectionTitle3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Class Feed.
        /// </summary>
        public static string FeaturesSectionTitle4
        {
            get
            {
                return ResourceManager.GetString("FeaturesSectionTitle4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Schools .
        /// </summary>
        public static string FeaturesSectionTitle5
        {
            get
            {
                return ResourceManager.GetString("FeaturesSectionTitle5", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spitball’s app.
        /// </summary>
        public static string FeaturesSectionTitle6
        {
            get
            {
                return ResourceManager.GetString("FeaturesSectionTitle6", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use Spitball to study with your friends and get better grades!.
        /// </summary>
        public static string FeaturesSubTitle
        {
            get
            {
                return ResourceManager.GetString("FeaturesSubTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spitball can help revolutionize the way you study: Whether you’ve missed your last class and are scrambling to get class notes, have a question regarding a particularly annoying assignment, or just looking for a way to test your knowledge before your finals - Spitball has got you covered! Sign up for free, find your school and your courses and start Spitballing with your friends!.
        /// </summary>
        public static string FeaturesText
        {
            get
            {
                return ResourceManager.GetString("FeaturesText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Our Features.
        /// </summary>
        public static string FeaturesTitle
        {
            get
            {
                return ResourceManager.GetString("FeaturesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open a free spitball account and pick your school - there are more than 325 schools available. If you cannot find your school there is still a lot you can do: Find a relevant class material from other schools, or be the first to add your school and help us build the community (and hey, you might even make a few bucks). Now you can find and Join your class, there are more than 57,00 classes waiting just for you. Find the material you need and start studying with your classmates. Ask questions, share ideas an [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProductText
        {
            get
            {
                return ResourceManager.GetString("ProductText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start studying like a pro with Spitball by following a few simple steps:.
        /// </summary>
        public static string ProductTextBegining
        {
            get
            {
                return ResourceManager.GetString("ProductTextBegining", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use Spitball like a Pro.
        /// </summary>
        public static string ProductTitle
        {
            get
            {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
    }
}
