//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mvc4WebRole.Views.User.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GamificationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GamificationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mvc4WebRole.Views.User.Resources.GamificationResources", typeof(GamificationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        public static string Badge {
            get {
                return ResourceManager.GetString("Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create 5 Quizzes.
        /// </summary>
        public static string BadgeCreateQuizzesDescription {
            get {
                return ResourceManager.GetString("BadgeCreateQuizzesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow 3 Classes.
        /// </summary>
        public static string BadgeFollowClassDescription {
            get {
                return ResourceManager.GetString("BadgeFollowClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like 50 posts or docs that you think are of great value to unlock this badge.
        /// </summary>
        public static string BadgeLikesDescription {
            get {
                return ResourceManager.GetString("BadgeLikesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string BadgeRegisterDescription {
            get {
                return ResourceManager.GetString("BadgeRegisterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        public static string Badges {
            get {
                return ResourceManager.GetString("Badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one job: upload 15 documents to your class.
        /// </summary>
        public static string BadgeUploadFilesDescription {
            get {
                return ResourceManager.GetString("BadgeUploadFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points System.
        /// </summary>
        public static string GamificationTableTitle {
            get {
                return ResourceManager.GetString("GamificationTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string Leaderboard {
            get {
                return ResourceManager.GetString("Leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string LeaderboardShowAll {
            get {
                return ResourceManager.GetString("LeaderboardShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show My Rank.
        /// </summary>
        public static string LeaderboardShowMySelf {
            get {
                return ResourceManager.GetString("LeaderboardShowMySelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Spitball! Sure, you just started, but you have a promising career ahead of you. Work hard and you’ll be rewarded with wisdom, Spitball swag, and an abundance of points!.
        /// </summary>
        public static string Level1Description {
            get {
                return ResourceManager.GetString("Level1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’re no longer the new kid at school! Training wheels have been removed. There is still much to learn and achieve. Study on, Young Gun!.
        /// </summary>
        public static string Level2Description {
            get {
                return ResourceManager.GetString("Level2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It’s clear you know what you’re doing. Young Spitballers rely on you for wisdom and knowledge. Yet, a smart student knows there is still much to learn!.
        /// </summary>
        public static string Level3Description {
            get {
                return ResourceManager.GetString("Level3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other students in the class look up to you. There’s a reason your parents always told you that you were special!.
        /// </summary>
        public static string Level4Description {
            get {
                return ResourceManager.GetString("Level4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ve achieved far more than the average student – you will forever be known as a Spitball Legend..
        /// </summary>
        public static string Level5Description {
            get {
                return ResourceManager.GetString("Level5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Level in.
        /// </summary>
        public static string NextLevelTItle {
            get {
                return ResourceManager.GetString("NextLevelTItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
    }
}
