//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mvc4WebRole.Views.User.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mvc4WebRole.Views.User.Resources.UserResources", typeof(UserResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All friends.
        /// </summary>
        public static string AllFriends {
            get {
                return ResourceManager.GetString("AllFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses / Groups.
        /// </summary>
        public static string CoursesGroups {
            get {
                return ResourceManager.GetString("CoursesGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses List.
        /// </summary>
        public static string CoursesList {
            get {
                return ResourceManager.GetString("CoursesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn points by:.
        /// </summary>
        public static string EarnBy {
            get {
                return ResourceManager.GetString("EarnBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account.
        /// </summary>
        public static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find friends from your contacts.
        /// </summary>
        public static string FindFriends {
            get {
                return ResourceManager.GetString("FindFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to question.
        /// </summary>
        public static string GotoQuestion {
            get {
                return ResourceManager.GetString("GotoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In common.
        /// </summary>
        public static string InCommon {
            get {
                return ResourceManager.GetString("InCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join date.
        /// </summary>
        public static string JoinDate {
            get {
                return ResourceManager.GetString("JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No answers to show.
        /// </summary>
        public static string NoAnswers {
            get {
                return ResourceManager.GetString("NoAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files to show.
        /// </summary>
        public static string NoFiles {
            get {
                return ResourceManager.GetString("NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No questions to show.
        /// </summary>
        public static string NoQuestions {
            get {
                return ResourceManager.GetString("NoQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not following any courses.
        /// </summary>
        public static string NotFollowing {
            get {
                return ResourceManager.GetString("NotFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 pts Upload an item to a Course.
        /// </summary>
        public static string PointsTxt1 {
            get {
                return ResourceManager.GetString("PointsTxt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 pts Each accepted invite to join.
        /// </summary>
        public static string PointsTxt2 {
            get {
                return ResourceManager.GetString("PointsTxt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 pts Receiving a 5 star rating.
        /// </summary>
        public static string PointsTxt3 {
            get {
                return ResourceManager.GetString("PointsTxt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 pts Receiving a 4 star rating.
        /// </summary>
        public static string PointsTxt4 {
            get {
                return ResourceManager.GetString("PointsTxt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 pts Receiving a 3 star rating.
        /// </summary>
        public static string PointsTxt5 {
            get {
                return ResourceManager.GetString("PointsTxt5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 pts Asking a question.
        /// </summary>
        public static string PointsTxt6 {
            get {
                return ResourceManager.GetString("PointsTxt6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 pts Answering a question.
        /// </summary>
        public static string PointsTxt7 {
            get {
                return ResourceManager.GetString("PointsTxt7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 pts for sharing on FB.
        /// </summary>
        public static string PointsTxt8 {
            get {
                return ResourceManager.GetString("PointsTxt8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University members.
        /// </summary>
        public static string UniMembers {
            get {
                return ResourceManager.GetString("UniMembers", resourceCulture);
            }
        }
    }
}
