//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mvc4WebRole.Views.Account.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mvc4WebRole.Views.Account.Resources.AccountResource", typeof(AccountResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send another request.
        /// </summary>
        public static string AnotherRequest {
            get {
                return ResourceManager.GetString("AnotherRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your email address.
        /// </summary>
        public static string ChangeMail {
            get {
                return ResourceManager.GetString("ChangeMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change theme.
        /// </summary>
        public static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        public static string ChangeThemeLight {
            get {
                return ResourceManager.GetString("ChangeThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change university.
        /// </summary>
        public static string changeUniversityBtn {
            get {
                return ResourceManager.GetString("changeUniversityBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your spam folder or.
        /// </summary>
        public static string CheckEmailSpam {
            get {
                return ResourceManager.GetString("CheckEmailSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t receive the email?.
        /// </summary>
        public static string DidntReceivedEmail {
            get {
                return ResourceManager.GetString("DidntReceivedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve emailed you a new password.
        /// </summary>
        public static string EmailedPassword {
            get {
                return ResourceManager.GetString("EmailedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notification.
        /// </summary>
        public static string EmailNotification {
            get {
                return ResourceManager.GetString("EmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string EmailSettingsSubscribe {
            get {
                return ResourceManager.GetString("EmailSettingsSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        public static string EmailSettingsUnsubscribe {
            get {
                return ResourceManager.GetString("EmailSettingsUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email address associated with your Spitball account. You will receive a link to reset your password to this email account shortly.
        /// </summary>
        public static string EmailToReset {
            get {
                return ResourceManager.GetString("EmailToReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to receive the password reset mail, you will be added to the Spitball mailing list. You can unsubscribe after the password reset has been complete through the &quot;User Settings&quot; screen of your Spitball account.
        /// </summary>
        public static string EmailUnsubscribeWarning {
            get {
                return ResourceManager.GetString("EmailUnsubscribeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        public static string EnterVerification {
            get {
                return ResourceManager.GetString("EnterVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string NotificationOwner {
            get {
                return ResourceManager.GetString("NotificationOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal account.
        /// </summary>
        public static string ProfileAccount {
            get {
                return ResourceManager.GetString("ProfileAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset instructions..
        /// </summary>
        public static string ResetInstructions {
            get {
                return ResourceManager.GetString("ResetInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string SelectImg {
            get {
                return ResourceManager.GetString("SelectImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A verification code was sent to your new email.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
    }
}
