//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mvc4WebRole.Views.Account.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mvc4WebRole.Views.Account.Resources.HomePageResources", typeof(HomePageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empowering Students to succeed by collaboratively sharing knowledge, in an open social studying network..
        /// </summary>
        public static string A4 {
            get {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for FREE.
        /// </summary>
        public static string A5 {
            get {
                return ResourceManager.GetString("A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitball is built by students and for students.
        /// </summary>
        public static string A6 {
            get {
                return ResourceManager.GetString("A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitball Features.
        /// </summary>
        public static string B1 {
            get {
                return ResourceManager.GetString("B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students learning from students. Quizzes make your own, or test yourself from the thousands already available..
        /// </summary>
        public static string B10 {
            get {
                return ResourceManager.GetString("B10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take allok at the some of these features that makes Spitball so unique..
        /// </summary>
        public static string B2 {
            get {
                return ResourceManager.GetString("B2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVAILABLE EVERYWHERE.
        /// </summary>
        public static string B3 {
            get {
                return ResourceManager.GetString("B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study when it suits you, from every computer, mobile or tablet you have.
        ///.
        /// </summary>
        public static string B4 {
            get {
                return ResourceManager.GetString("B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUESTIONS AND ANSWERS.
        /// </summary>
        public static string B5 {
            get {
                return ResourceManager.GetString("B5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions about yesterday&apos;s class, what paper is due next week? What is the right answer on question #7? Spitball is here to help. Ask a question, get an answer from a fellow student.
        /// </summary>
        public static string B6 {
            get {
                return ResourceManager.GetString("B6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WATCH AND SHARE.
        /// </summary>
        public static string B7 {
            get {
                return ResourceManager.GetString("B7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to online lectures, share and compare class notes, review reading material, discuss in the privacy of your study group, all in one place..
        /// </summary>
        public static string B8 {
            get {
                return ResourceManager.GetString("B8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quizzes and Review Sheets.
        /// </summary>
        public static string B9 {
            get {
                return ResourceManager.GetString("B9", resourceCulture);
            }
        }
    }
}
