//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Zbox.Mvc3WebRole.Views.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Zbox.Mvc3WebRole.Views.Dashboard.Resources.IndexResources", typeof(IndexResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes.
        /// </summary>
        public static string Boxes {
            get {
                return ResourceManager.GetString("Boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search course name or instructor.
        /// </summary>
        public static string InlineSearch {
            get {
                return ResourceManager.GetString("InlineSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        public static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My private.
        /// </summary>
        public static string MyPrivate {
            get {
                return ResourceManager.GetString("MyPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tag.
        /// </summary>
        public static string OpenTag {
            get {
                return ResourceManager.GetString("OpenTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned by me.
        /// </summary>
        public static string OwnedByMe {
            get {
                return ResourceManager.GetString("OwnedByMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending invitations.
        /// </summary>
        public static string PendingInvitations {
            get {
                return ResourceManager.GetString("PendingInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result for.
        /// </summary>
        public static string ResultFor {
            get {
                return ResourceManager.GetString("ResultFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My boxes.
        /// </summary>
        public static string SearchMyBoxes {
            get {
                return ResourceManager.GetString("SearchMyBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page.
        /// </summary>
        public static string SearchThisPage {
            get {
                return ResourceManager.GetString("SearchThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared by me.
        /// </summary>
        public static string SharedByMe {
            get {
                return ResourceManager.GetString("SharedByMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared by others.
        /// </summary>
        public static string SharedByOthers {
            get {
                return ResourceManager.GetString("SharedByOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starred.
        /// </summary>
        public static string Starred {
            get {
                return ResourceManager.GetString("Starred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POPULAR TAGS.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to find tags.
        /// </summary>
        public static string TypeTag {
            get {
                return ResourceManager.GetString("TypeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
    }
}
