//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mvc4WebRole.Views.University.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UniversityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UniversityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mvc4WebRole.Views.University.Resources.UniversityResources", typeof(UniversityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a class.
        /// </summary>
        public static string AddClass {
            get {
                return ResourceManager.GetString("AddClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a department.
        /// </summary>
        public static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your school.
        /// </summary>
        public static string AddSchool {
            get {
                return ResourceManager.GetString("AddSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t see your class? Create it..
        /// </summary>
        public static string ClassChooseBottomSearchResultTitle {
            get {
                return ResourceManager.GetString("ClassChooseBottomSearchResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Class.
        /// </summary>
        public static string classChoosePopupTitle {
            get {
                return ResourceManager.GetString("classChoosePopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        public static string ClassChooseYellowClickHere {
            get {
                return ResourceManager.GetString("ClassChooseYellowClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve added.
        /// </summary>
        public static string ClassChooseYellowTitle1 {
            get {
                return ResourceManager.GetString("ClassChooseYellowTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue selecting classes.
        /// </summary>
        public static string ClassChooseYellowTitle2 {
            get {
                return ResourceManager.GetString("ClassChooseYellowTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you&apos;re done.
        /// </summary>
        public static string ClassChooseYellowTitle3 {
            get {
                return ResourceManager.GetString("ClassChooseYellowTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department settings.
        /// </summary>
        public static string DepartmentSettings {
            get {
                return ResourceManager.GetString("DepartmentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the class details and make Spitball more useful .
        /// </summary>
        public static string EmptyStateTopNodeText {
            get {
                return ResourceManager.GetString("EmptyStateTopNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeesh… we’re feeling a little exposed here.
        /// </summary>
        public static string EmptyStateTopNodeTitle {
            get {
                return ResourceManager.GetString("EmptyStateTopNodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Class Name .
        /// </summary>
        public static string EnterClassName {
            get {
                return ResourceManager.GetString("EnterClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Number (optional).
        /// </summary>
        public static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Department Name.
        /// </summary>
        public static string EnterDepName {
            get {
                return ResourceManager.GetString("EnterDepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your 9 digit ID.
        /// </summary>
        public static string EnterID {
            get {
                return ResourceManager.GetString("EnterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University name must be more than 1 character.
        /// </summary>
        public static string EntryLength {
            get {
                return ResourceManager.GetString("EntryLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id must be 9 characters long.
        /// </summary>
        public static string IdLengthError {
            get {
                return ResourceManager.GetString("IdLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor (optional).
        /// </summary>
        public static string Instructor {
            get {
                return ResourceManager.GetString("Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more schools found.
        /// </summary>
        public static string NoMoreSchools {
            get {
                return ResourceManager.GetString("NoMoreSchools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new class.
        /// </summary>
        public static string OnboardingCreateClass {
            get {
                return ResourceManager.GetString("OnboardingCreateClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Spitball! Start by selecting your first class..
        /// </summary>
        public static string OnboardingHeaderStep1 {
            get {
                return ResourceManager.GetString("OnboardingHeaderStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select another class.
        /// </summary>
        public static string OnboardingHeaderStep2 {
            get {
                return ResourceManager.GetString("OnboardingHeaderStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by class name or department.
        /// </summary>
        public static string OnboardingSearchContainer {
            get {
                return ResourceManager.GetString("OnboardingSearchContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find any Class or Department.
        ///Try to search again or add this class to our listings..
        /// </summary>
        public static string OnboardingSearchEmptyState {
            get {
                return ResourceManager.GetString("OnboardingSearchEmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School name.
        /// </summary>
        public static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ready to do something big for you and your classmates.
        /// </summary>
        public static string UniversityAddSchoolTitle {
            get {
                return ResourceManager.GetString("UniversityAddSchoolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your school.
        /// </summary>
        public static string UniversitySearchPlaceholder {
            get {
                return ResourceManager.GetString("UniversitySearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your school to start 
        ///Spitballing with your classmates.
        /// </summary>
        public static string UniversitySearchTitle {
            get {
                return ResourceManager.GetString("UniversitySearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um... We can&apos;t find your school in our records
        ///.
        /// </summary>
        public static string UniversitySearchTitleNoResult {
            get {
                return ResourceManager.GetString("UniversitySearchTitleNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try different keywords or add your own.
        /// </summary>
        public static string UniversitySearchTitleNoResultSub {
            get {
                return ResourceManager.GetString("UniversitySearchTitleNoResultSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let’s Spitball!.
        /// </summary>
        public static string UniversitySearchTitleTyping {
            get {
                return ResourceManager.GetString("UniversitySearchTitleTyping", resourceCulture);
            }
        }
    }
}
