
// DIALOGS:
export const PAYMENT_DIALOG = 'PAYMENT_DIALOG';
export const ITEM_DIALOG = 'ITEM_DIALOG';
export const SESSION_CREATE_DIALOG = 'SESSION_CREATE_DIALOG';


// Create Broadcast
export const CREATE_BROADCAST_ERROR = 'CREATE_BROADCAST_ERROR'

// PROFILE PAGE

//TUTOR EDIT PROFILE COMPONENT
// export const TUTOR_EDIT_PROFILE = 'TUTOR_EDIT_PROFILE'
// AUTHS:
export const REGISTER = 'register';

// TOASTERS:
export const PURCHASE_TRANSACTION = 'PURCHASE_TRANSACTION';

// TOASTERS: ERRORS:
export const BOOK_FAILED = 'BOOK_FAILED';
export const WENT_WRONG = 'WENT_WRONG';
export const FILE_NOT_SUPPORTED = 'FILE_NOT_SUPPORTED';
export const ENROLLED_ERROR = 'ENROLLED_ERROR';
