
// DIALOGS:
export const PAYMENT_DIALOG = 'PAYMENT_DIALOG';



// PROFILE PAGE

//TUTOR EDIT PROFILE COMPONENT
export const TUTOR_EDIT_PROFILE = 'TUTOR_EDIT_PROFILE'
// AUTHS:
export const REGISTER = 'register';


// TOASTERS:
export const BOOK_FAILED = 'BOOK_FAILED';
export const WENT_WRONG = 'WENT_WRONG';
export const FILE_NOT_SUPPORTED = 'FILE_NOT_SUPPORTED';
