//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mvc4WebRole.Views.Store.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mvc4WebRole.Views.Store.Resources.StoreResources", typeof(StoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אודות.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אודות קלאודנטס.
        /// </summary>
        public static string AboutCloudents {
            get {
                return ResourceManager.GetString("AboutCloudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפעל את הקופון.
        /// </summary>
        public static string ActivateCoupon {
            get {
                return ResourceManager.GetString("ActivateCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רחוב ומספר.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף לרכישה.
        /// </summary>
        public static string AddToPurchase {
            get {
                return ResourceManager.GetString("AddToPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כדאי לדעת לפני הקניה:.
        /// </summary>
        public static string BeforeYouBuy {
            get {
                return ResourceManager.GetString("BeforeYouBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא לחייב אותי ב.
        /// </summary>
        public static string BillMe {
            get {
                return ResourceManager.GetString("BillMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם בעל הכרטיס.
        /// </summary>
        public static string CardOwnerName {
            get {
                return ResourceManager.GetString("CardOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ת.ז. בעל הכרטיס.
        /// </summary>
        public static string CardOwnerNo {
            get {
                return ResourceManager.GetString("CardOwnerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון נייד.
        /// </summary>
        public static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אספקת המוצר תהא ישירות מהספק/יבואן וכפועל יוצא מחירי המוצרים הנמכרים באתר מוזלים במיוחד. .
        /// </summary>
        public static string CheapPrices {
            get {
                return ResourceManager.GetString("CheapPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ישוב.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הערות.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צור קשר.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר כולל משלוח.
        /// </summary>
        public static string CostWithShipping {
            get {
                return ResourceManager.GetString("CostWithShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קופון.
        /// </summary>
        public static string Coupon {
            get {
                return ResourceManager.GetString("Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קוד הקופון נקלט בהצלחה.
        /// </summary>
        public static string CouponActivated {
            get {
                return ResourceManager.GetString("CouponActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר כרטיס אשראי.
        /// </summary>
        public static string CreditCardNo {
            get {
                return ResourceManager.GetString("CreditCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אתר שלפניכם מציע הטבות המיועדות עבורכם בלבד..
        /// </summary>
        public static string DiscountsForYou {
            get {
                return ResourceManager.GetString("DiscountsForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דואר אלקטרוני.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אנא מלא את פרטיך לצורך השלמת הרכישה..
        /// </summary>
        public static string FillDetails {
            get {
                return ResourceManager.GetString("FillDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הזכאות למחירים מיוחדים, כולל הנחת קופון, הנה לסטודנטים רשומים בלבד. כל שעליכם לעשות הוא להירשם לאתר או להשתמש בקוד הקופון אשר ברשותכם בשילוב מספר תעודת סטודנט\ ת.ז.
        ///תהנו!.
        /// </summary>
        public static string GetDiscounts {
            get {
                return ResourceManager.GetString("GetDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בכל שאלה או בעיה בה נתקלת לגבי השימוש באתר או המוצרים הנמכרים בו, אנא מלא טופס זה, ונציגנו יחזור אליך בהקדם, או צור קשר בטלפון 09-8989819.
        /// </summary>
        public static string GetHelp {
            get {
                return ResourceManager.GetString("GetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עמוד הבית.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מבצעים חמים.
        /// </summary>
        public static string HotSales {
            get {
                return ResourceManager.GetString("HotSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר תעודת סטודנט/ת.ז..
        /// </summary>
        public static string IdentityNo {
            get {
                return ResourceManager.GetString("IdentityNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תשלומים..
        /// </summary>
        public static string Installments {
            get {
                return ResourceManager.GetString("Installments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קראתי את התקנון ואני מסכים לתנאי השימוש..
        /// </summary>
        public static string IReadIt {
            get {
                return ResourceManager.GetString("IReadIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כניסה.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לפרטים.
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הנחה.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הזמן.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר כולל מע&apos;&apos;מ.
        /// </summary>
        public static string PriceWithVat {
            get {
                return ResourceManager.GetString("PriceWithVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשך לתשלום.
        /// </summary>
        public static string ProceedTo {
            get {
                return ResourceManager.GetString("ProceedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המאגר האקדמי הרשמי של מוצרים לסטודנטים.
        /// </summary>
        public static string ProductDiscounts {
            get {
                return ResourceManager.GetString("ProductDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם המוצר.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר המוצר.
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוצרים.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רכוש עכשיו.
        /// </summary>
        public static string PurchaseNow {
            get {
                return ResourceManager.GetString("PurchaseNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר רגיל.
        /// </summary>
        public static string RegPrice {
            get {
                return ResourceManager.GetString("RegPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מצאנו עבורך מוצרים נוספים שיכולים לעניין אותך.
        /// </summary>
        public static string RelatedProducts {
            get {
                return ResourceManager.GetString("RelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אספקה בטוחה:.
        /// </summary>
        public static string SafeDelivery {
            get {
                return ResourceManager.GetString("SafeDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חפש.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הנתונים בעמוד זה מאובטחים בטכנולוגיית SSL.
        /// </summary>
        public static string SecuredPage {
            get {
                return ResourceManager.GetString("SecuredPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בטחון בקניה:.
        /// </summary>
        public static string SecurePurchase {
            get {
                return ResourceManager.GetString("SecurePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מתוך רצון לספק את הביטחון המקסימאלי בקניה, השקענו משאבים רבים באבטחת מידע ושמירת הפרטיות. העסקאות המתבצעות באתר מאובטחות בטכנולוגית SSL המאושרת ע&quot;י חברות האשראי, וכל המידע המועבר בדבר פרטי האשראי שלך מוצפן..
        /// </summary>
        public static string SecureSite {
            get {
                return ResourceManager.GetString("SecureSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אבטחת מידע:.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משלוח.
        /// </summary>
        public static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דמי משלוח.
        /// </summary>
        public static string ShippingCost {
            get {
                return ResourceManager.GetString("ShippingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרשמה.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האתר מופעל ע&quot;י חברת ביזפוינט בע&quot;מ ח.פ 512900473 בשיתוף עם אגודות הסטודנטים. החברה נוסדה בשנת 2000 ומתמחה בשיווק ישיר וסחר אלקטרוני באינטרנט והנה אחת מהמובילות בתחומה בארץ. בין השותפים בחברה קבוצת מרחב בע&quot;מ, חברת אל-רוב (ישראל) בע&quot;מ ,חברת שרידב בע&quot;מ. אספקת המוצרים הנה ישירות ממחסני הספקים/יבואני המוצרים השונים ובאחריותם. ספקי המוצרים מהמובילים בארץ בתחומם, נבחרו בקפידה, עם מתן דגש על רמת המוצרים ומתן השירות. .
        /// </summary>
        public static string SitePoweredBy {
            get {
                return ResourceManager.GetString("SitePoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נרכשו.
        /// </summary>
        public static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אתר ההטבות לסטודנטים.
        /// </summary>
        public static string StudentDiscounts {
            get {
                return ResourceManager.GetString("StudentDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לסטודנט.
        /// </summary>
        public static string StudentPrice {
            get {
                return ResourceManager.GetString("StudentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר לסטודנט.
        /// </summary>
        public static string StudentPrice2 {
            get {
                return ResourceManager.GetString("StudentPrice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תנאי שימוש.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 ספרות בגב הכרטיס.
        /// </summary>
        public static string ThreeDigits {
            get {
                return ResourceManager.GetString("ThreeDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לקבלת קוד קופון עליך להירשם לאתר או פנה לאגודת הסטודנטים בה אתה חבר.
        /// </summary>
        public static string ToGetACoupon {
            get {
                return ResourceManager.GetString("ToGetACoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&apos;&apos;כ לתשלום.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שדרוגים ותוספות.
        /// </summary>
        public static string Upgrades {
            get {
                return ResourceManager.GetString("Upgrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוקף.
        /// </summary>
        public static string Vaildity {
            get {
                return ResourceManager.GetString("Vaildity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מע&apos;&apos;מ.
        /// </summary>
        public static string Vat {
            get {
                return ResourceManager.GetString("Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אנו מתחייבים כי בכל רכישה שלך באמצעות האתר תקבל את המוצר שהזמנת. במידה ולא - אנו מתחייבים להחזר כספי מלא. .
        /// </summary>
        public static string WeCommit {
            get {
                return ResourceManager.GetString("WeCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברוכים הבאים לחנות האגודה.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מה זה?.
        /// </summary>
        public static string WhatIsThis {
            get {
                return ResourceManager.GetString("WhatIsThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חפש מוצר: טאבלט, מדפסת, מילון....
        /// </summary>
        public static string WhatProduct {
            get {
                return ResourceManager.GetString("WhatProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחירים מהיבואן לצרכן:.
        /// </summary>
        public static string WholeToRetail {
            get {
                return ResourceManager.GetString("WholeToRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קוד הקופון אינו תקין.
        /// </summary>
        public static string WrongCode {
            get {
                return ResourceManager.GetString("WrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ההזמנה שלך.
        /// </summary>
        public static string YourOrder {
            get {
                return ResourceManager.GetString("YourOrder", resourceCulture);
            }
        }
    }
}
