//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Zbox.Infrastructure.Mail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Zbox.Infrastructure.Mail.Resources.EmailResource", typeof(EmailResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        internal static string answers {
            get {
                return ResourceManager.GetString("answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Your Class Online.
        /// </summary>
        internal static string CoursesLowActivitySubject {
            get {
                return ResourceManager.GetString("CoursesLowActivitySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ever notice how your courses never has anything posted in it? 
        ///Change that by inviting a classmate via Facebook or email and uploading a doc that you want them to see..
        /// </summary>
        internal static string CoursesLowActivityText {
            get {
                return ResourceManager.GetString("CoursesLowActivityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite to {0}.
        /// </summary>
        internal static string InviteSubject {
            get {
                return ResourceManager.GetString("InviteSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string item {
            get {
                return ResourceManager.GetString("item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your esteemed classmates hold your Spitball posts in the highest regard. Keep posting documents, quizzes, and comments to improve Spitball for everyone..
        /// </summary>
        internal static string LikesMailFooter {
            get {
                return ResourceManager.GetString("LikesMailFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} likes your {1} {2}.
        /// </summary>
        internal static string LikesMailLineDetails {
            get {
                return ResourceManager.GetString("LikesMailLineDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have New Likes on Spitball.
        /// </summary>
        internal static string LikesMailSubject {
            get {
                return ResourceManager.GetString("LikesMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} more likes on your Spitball posts:
        ///Check them out:.
        /// </summary>
        internal static string LikesMailTitle {
            get {
                return ResourceManager.GetString("LikesMailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your courses.
        /// </summary>
        internal static string NoFollowBoxSubject {
            get {
                return ResourceManager.GetString("NoFollowBoxSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitball’s course listing is always expanding and open to everyone. 
        ///Search for courses made by your classmates to start sharing notes and quizzes. 
        ///If you can’t find your course, make Spitball that much more useful by creating it!.
        /// </summary>
        internal static string NoFollowBoxText {
            get {
                return ResourceManager.GetString("NoFollowBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting Your School.
        /// </summary>
        internal static string NoUniversitySubject {
            get {
                return ResourceManager.GetString("NoUniversitySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are so happy that you have chosen Spitball, but it works best for you when you have selected a school! 
        ///Once you select your school, you can follow or create the courses 
        ///you are enrolled in. 
        ///From there, you can message your classmates directly with questions on homework, share and compare uploaded notes, create quizzes and more! 
        ///Log in to pick your school and find your courses now!.
        /// </summary>
        internal static string NoUniversityText {
            get {
                return ResourceManager.GetString("NoUniversityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string questions {
            get {
                return ResourceManager.GetString("questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        internal static string ReplyToCommentLink {
            get {
                return ResourceManager.GetString("ReplyToCommentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone commented on your post.
        /// </summary>
        internal static string ReplyToCommentSubject {
            get {
                return ResourceManager.GetString("ReplyToCommentSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} commented on a post you made on {1}.
        ///{2} to read what your classmate wrote and respond to their post. Spitball is all about being social, after all..
        /// </summary>
        internal static string ReplyToCommentText {
            get {
                return ResourceManager.GetString("ReplyToCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding Friends, Uploading Notes.
        /// </summary>
        internal static string UniversityLowActivitySubject {
            get {
                return ResourceManager.GetString("UniversityLowActivitySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your university’s Spitball page needs a little work… Be the study pioneer your classmates need and start uploading notes and inviting friends to join you via email..
        /// </summary>
        internal static string UniversityLowActivityText {
            get {
                return ResourceManager.GetString("UniversityLowActivityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Spitball.
        /// </summary>
        internal static string WelcomeSubject {
            get {
                return ResourceManager.GetString("WelcomeSubject", resourceCulture);
            }
        }
    }
}
