//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mvc4WebRole.Js.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mvc4WebRole.Js.Resources.JsResources", typeof(JsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active member.
        /// </summary>
        public static string ActiveMember {
            get {
                return ResourceManager.GetString("ActiveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your comment.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitball is the most advanced free online and mobile social studying platform. Join the social studying revolution with Spitball now..
        /// </summary>
        public static string CloudentsJoin {
            get {
                return ResourceManager.GetString("CloudentsJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code you entered is incorrect.
        /// </summary>
        public static string CodeIncorrect {
            get {
                return ResourceManager.GetString("CodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code should be numeric.
        /// </summary>
        public static string CodeNumeric {
            get {
                return ResourceManager.GetString("CodeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails don&apos;t match.
        /// </summary>
        public static string ConfirmEmailCompare {
            get {
                return ResourceManager.GetString("ConfirmEmailCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes I follow.
        /// </summary>
        public static string CoursesFollow {
            get {
                return ResourceManager.GetString("CoursesFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this class will delete all its content including files and Q&amp;A. Are you sure you would like to delete this course?.
        /// </summary>
        public static string DeleteCourse {
            get {
                return ResourceManager.GetString("DeleteCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting folder.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email changed.
        /// </summary>
        public static string EmailChanged {
            get {
                return ResourceManager.GetString("EmailChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        public static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagged.
        /// </summary>
        public static string Flagged {
            get {
                return ResourceManager.GetString("Flagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder.
        /// </summary>
        public static string FolderCreate {
            get {
                return ResourceManager.GetString("FolderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving items to folder.
        /// </summary>
        public static string FolderItemError {
            get {
                return ResourceManager.GetString("FolderItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename folder.
        /// </summary>
        public static string FolderRename {
            get {
                return ResourceManager.GetString("FolderRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I joined {0} on Spitball, our free online social studying platform.
        /// </summary>
        public static string IJoined {
            get {
                return ResourceManager.GetString("IJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file has incorrect extension.
        /// </summary>
        public static string IncorrectExtension {
            get {
                return ResourceManager.GetString("IncorrectExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite people to this Group Box using:.
        /// </summary>
        public static string InviteBox {
            get {
                return ResourceManager.GetString("InviteBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite people to this class using:.
        /// </summary>
        public static string InviteCourse {
            get {
                return ResourceManager.GetString("InviteCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I shared.
        /// </summary>
        public static string IShared {
            get {
                return ResourceManager.GetString("IShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave group.
        /// </summary>
        public static string LeaveGroup {
            get {
                return ResourceManager.GetString("LeaveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min. ago.
        /// </summary>
        public static string MinAgo {
            get {
                return ResourceManager.GetString("MinAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to follow this box.
        /// </summary>
        public static string NeedToFollowBox {
            get {
                return ResourceManager.GetString("NeedToFollowBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on Spitball.
        /// </summary>
        public static string OnCloudents {
            get {
                return ResourceManager.GetString("OnCloudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 6 characters.
        /// </summary>
        public static string PwdAtLeast6Chars {
            get {
                return ResourceManager.GetString("PwdAtLeast6Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was successfully changed.
        /// </summary>
        public static string PwdChanged {
            get {
                return ResourceManager.GetString("PwdChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error renaming folder.
        /// </summary>
        public static string RenameError {
            get {
                return ResourceManager.GetString("RenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sept.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this Group Box.
        /// </summary>
        public static string ShareBox {
            get {
                return ResourceManager.GetString("ShareBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this class.
        /// </summary>
        public static string ShareCourse {
            get {
                return ResourceManager.GetString("ShareCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want.
        /// </summary>
        public static string SureYouWantTo {
            get {
                return ResourceManager.GetString("SureYouWantTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string SureYouWantToDelete {
            get {
                return ResourceManager.GetString("SureYouWantToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to delete this box?.
        /// </summary>
        public static string ToDeleteBox {
            get {
                return ResourceManager.GetString("ToDeleteBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to leave this group?.
        /// </summary>
        public static string ToLeaveGroup {
            get {
                return ResourceManager.GetString("ToLeaveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow.
        /// </summary>
        public static string Unfollow {
            get {
                return ResourceManager.GetString("Unfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded files.
        /// </summary>
        public static string UploadedFiles {
            get {
                return ResourceManager.GetString("UploadedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading files.
        /// </summary>
        public static string UploadingFiles {
            get {
                return ResourceManager.GetString("UploadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email.
        /// </summary>
        public static string UsernameOr {
            get {
                return ResourceManager.GetString("UsernameOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
