//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mvc4WebRole.Js.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mvc4WebRole.Js.Resources.JsResources", typeof(JsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new email was saved.
        /// </summary>
        public static string changeEmailSuccess {
            get {
                return ResourceManager.GetString("changeEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to delete this department?.
        /// </summary>
        public static string deleteDepartment {
            get {
                return ResourceManager.GetString("deleteDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to delete this item?.
        /// </summary>
        public static string deleteItem {
            get {
                return ResourceManager.GetString("deleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to delete this post?.
        /// </summary>
        public static string deletePost {
            get {
                return ResourceManager.GetString("deletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to delete this quiz?.
        /// </summary>
        public static string deleteQuiz {
            get {
                return ResourceManager.GetString("deleteQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to delete this reply?.
        /// </summary>
        public static string deleteReply {
            get {
                return ResourceManager.GetString("deleteReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to delete this tab?.
        /// </summary>
        public static string deleteTab {
            get {
                return ResourceManager.GetString("deleteTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string dialogCancel {
            get {
                return ResourceManager.GetString("dialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string dialogOk {
            get {
                return ResourceManager.GetString("dialogOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password was saved.
        /// </summary>
        public static string passwordChangeSuccess {
            get {
                return ResourceManager.GetString("passwordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want in? Ask the owner for access.
        /// </summary>
        public static string privateDepPopupContent {
            get {
                return ResourceManager.GetString("privateDepPopupContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive an email if and when the owner approves your request..
        /// </summary>
        public static string privateDepPopupContentOnSend {
            get {
                return ResourceManager.GetString("privateDepPopupContentOnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request access.
        /// </summary>
        public static string privateDepPopupRequestButton {
            get {
                return ResourceManager.GetString("privateDepPopupRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need permission to access this section.
        /// </summary>
        public static string privateDepPopupTitle {
            get {
                return ResourceManager.GetString("privateDepPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for access has been sent..
        /// </summary>
        public static string privateDepPopupTitleOnSend {
            get {
                return ResourceManager.GetString("privateDepPopupTitleOnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave this page? The created quiz will NOT be saved.
        /// </summary>
        public static string quizCreateBrowserBack {
            get {
                return ResourceManager.GetString("quizCreateBrowserBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the correct answer.
        /// </summary>
        public static string quizCreateCorrectAnswer {
            get {
                return ResourceManager.GetString("quizCreateCorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to provide a minimum of 2 answers.
        /// </summary>
        public static string quizCreateNeedAnswers {
            get {
                return ResourceManager.GetString("quizCreateNeedAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide answers.
        /// </summary>
        public static string quizCreateNeedAnswerText {
            get {
                return ResourceManager.GetString("quizCreateNeedAnswerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide questions.
        /// </summary>
        public static string quizCreateNeedQuestionText {
            get {
                return ResourceManager.GetString("quizCreateNeedQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string quizDelete {
            get {
                return ResourceManager.GetString("quizDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this quiz as a draft for future editing
        ///(Only you are able to see and edit the draft).
        /// </summary>
        public static string quizLeaveContent {
            get {
                return ResourceManager.GetString("quizLeaveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t finished this quiz. Do you want to leave?.
        /// </summary>
        public static string quizLeaveTitle {
            get {
                return ResourceManager.GetString("quizLeaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as draft.
        /// </summary>
        public static string quizSaveAsDraft {
            get {
                return ResourceManager.GetString("quizSaveAsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update complete.
        /// </summary>
        public static string settingsChangeName {
            get {
                return ResourceManager.GetString("settingsChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string settingsDone {
            get {
                return ResourceManager.GetString("settingsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitball.
        /// </summary>
        public static string siteName {
            get {
                return ResourceManager.GetString("siteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitball has updated.
        /// </summary>
        public static string spitballUpdate {
            get {
                return ResourceManager.GetString("spitballUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your settings have been updated.
        /// </summary>
        public static string toasterBoxSettings {
            get {
                return ResourceManager.GetString("toasterBoxSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new private message!.
        /// </summary>
        public static string toasterChatMessage {
            get {
                return ResourceManager.GetString("toasterChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have created a study group.
        /// </summary>
        public static string toasterCreateBox {
            get {
                return ResourceManager.GetString("toasterCreateBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have created a course.
        /// </summary>
        public static string toasterCreateCourse {
            get {
                return ResourceManager.GetString("toasterCreateCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have created a department.
        /// </summary>
        public static string toasterCreateDepartment {
            get {
                return ResourceManager.GetString("toasterCreateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have Created A Quiz.
        /// </summary>
        public static string toasterCreateQuiz {
            get {
                return ResourceManager.GetString("toasterCreateQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access was granted
        ///.
        /// </summary>
        public static string toasterDepartmentApproved {
            get {
                return ResourceManager.GetString("toasterDepartmentApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have joined this class.
        /// </summary>
        public static string toasterFollowBox {
            get {
                return ResourceManager.GetString("toasterFollowBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Invite has been sent.
        /// </summary>
        public static string toasterInviteComplete {
            get {
                return ResourceManager.GetString("toasterInviteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked.
        /// </summary>
        public static string toasterLikeItem {
            get {
                return ResourceManager.GetString("toasterLikeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened.
        /// </summary>
        public static string toasterOpenSchool {
            get {
                return ResourceManager.GetString("toasterOpenSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Uploaded.
        /// </summary>
        public static string toasterUploadComplete {
            get {
                return ResourceManager.GetString("toasterUploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your image has been updated.
        /// </summary>
        public static string toasterUploadPic {
            get {
                return ResourceManager.GetString("toasterUploadPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to unfollow this class?.
        /// </summary>
        public static string unfollowClass {
            get {
                return ResourceManager.GetString("unfollowClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot contain spaces.
        /// </summary>
        public static string whiteSpaceError {
            get {
                return ResourceManager.GetString("whiteSpaceError", resourceCulture);
            }
        }
    }
}
