export const studyRoom_SETTERS = {
   ACTIVE_NAV_EDITOR: 'ACTIVE_NAV_EDITOR',
   ROOM_PROPS: 'ROOM_PROPS',
   ROOM_ACTIVE: 'ROOM_ACTIVE',
   ROOM_PAYMENT: 'ROOM_PAYMENT',
   ROOM_RESET: 'ROOM_RESET',
   DIALOG_ROOM_SETTINGS: 'DIALOG_ROOM_SETTINGS',
   DIALOG_END_SESSION: 'DIALOG_END_SESSION',
   DIALOG_USER_CONSENT: 'DIALOG_USER_CONSENT',
   DIALOG_SNAPSHOT: 'DIALOG_SNAPSHOT',
   ROOM_PARTICIPANT_COUNT: 'ROOM_PARTICIPANT_COUNT',
   ROOM_JOINED: 'ROOM_JOINED',
}