export const SETTERS = {
   JWT_TOKEN: 'JWT_TOKEN',
   DATA_TRACK: 'DATA_TRACK',
   VIDEO_TRACK: 'VIDEO_TRACK',
   VIDEO_AVAILABLE: 'VIDEO_AVAILABLE',
   VIDEO_TOGGLE: 'VIDEO_TOGGLE',
   AUDIO_TRACK: 'AUDIO_TRACK',
   AUDIO_AVAILABLE: 'AUDIO_AVAILABLE',
   AUDIO_TOGGLE: 'AUDIO_TOGGLE',
   FULL_SCREEN_AVAILABLE: 'FULL_SCREEN_AVAILABLE',
   SCREEN_SHARE: 'SCREEN_SHARE',
   IS_SCREEN_SHARE: 'IS_SCREEN_SHARE',
}