//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mobile.Views.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuizResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuizResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mobile.Views.Shared.Resources.QuizResources", typeof(QuizResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an answer.
        /// </summary>
        public static string AddAnswer {
            get {
                return ResourceManager.GetString("AddAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question.
        /// </summary>
        public static string AddQuestion {
            get {
                return ResourceManager.GetString("AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet, I&apos;m scared.
        /// </summary>
        public static string Afraid {
            get {
                return ResourceManager.GetString("Afraid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check answers.
        /// </summary>
        public static string CheckAnswers {
            get {
                return ResourceManager.GetString("CheckAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct errors.
        /// </summary>
        public static string CheckQuiz {
            get {
                return ResourceManager.GetString("CheckQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose to save the quiz as a &apos;draft&apos; for future editing (only you can see and edit the draft).
        /// </summary>
        public static string ChooseDraft {
            get {
                return ResourceManager.GetString("ChooseDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose quiz name.
        /// </summary>
        public static string ChooseName {
            get {
                return ResourceManager.GetString("ChooseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Answer.
        /// </summary>
        public static string CorrectAnswer {
            get {
                return ResourceManager.GetString("CorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a quiz.
        /// </summary>
        public static string CreateQuiz {
            get {
                return ResourceManager.GetString("CreateQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the quiz.
        /// </summary>
        public static string DeleteQuiz {
            get {
                return ResourceManager.GetString("DeleteQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Quiz.
        /// </summary>
        public static string EditQuiz {
            get {
                return ResourceManager.GetString("EditQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave this quiz?.
        /// </summary>
        public static string LeaveQuiz {
            get {
                return ResourceManager.GetString("LeaveQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiple choice questions.
        /// </summary>
        public static string MultipleChoice {
            get {
                return ResourceManager.GetString("MultipleChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No answer given.
        /// </summary>
        public static string NoAnswer {
            get {
                return ResourceManager.GetString("NoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t finished your quiz yet..
        /// </summary>
        public static string NotFinished {
            get {
                return ResourceManager.GetString("NotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of your classmates
        ///took this quiz.
        /// </summary>
        public static string OfYourMates {
            get {
                return ResourceManager.GetString("OfYourMates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview quiz.
        /// </summary>
        public static string PreviewQuiz {
            get {
                return ResourceManager.GetString("PreviewQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish the quiz.
        /// </summary>
        public static string PublishQuiz {
            get {
                return ResourceManager.GetString("PublishQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz summary.
        /// </summary>
        public static string QuizSummary {
            get {
                return ResourceManager.GetString("QuizSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to take a quiz.
        /// </summary>
        public static string QuizTime {
            get {
                return ResourceManager.GetString("QuizTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake quiz.
        /// </summary>
        public static string RetakeQuiz {
            get {
                return ResourceManager.GetString("RetakeQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as draft.
        /// </summary>
        public static string SaveDraft {
            get {
                return ResourceManager.GetString("SaveDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score distribution:.
        /// </summary>
        public static string ScoreDistribution {
            get {
                return ResourceManager.GetString("ScoreDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a chance.
        /// </summary>
        public static string TakeChance {
            get {
                return ResourceManager.GetString("TakeChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your time was.
        /// </summary>
        public static string TimeWas {
            get {
                return ResourceManager.GetString("TimeWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top three for this quiz:.
        /// </summary>
        public static string TopThree {
            get {
                return ResourceManager.GetString("TopThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong.
        /// </summary>
        public static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You got.
        /// </summary>
        public static string YouGot {
            get {
                return ResourceManager.GetString("YouGot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ready to
        ///test yourself?.
        /// </summary>
        public static string YouReady {
            get {
                return ResourceManager.GetString("YouReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your score.
        /// </summary>
        public static string YourScore {
            get {
                return ResourceManager.GetString("YourScore", resourceCulture);
            }
        }
    }
}
