//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zbang.Cloudents.Mvc4WebRole.Views.Item.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zbang.Cloudents.Mvc4WebRole.Views.Item.Resources.ItemsResources", typeof(ItemsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written by.
        /// </summary>
        public static string CommentAuthor {
            get {
                return ResourceManager.GetString("CommentAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item might be subject to certain laws and school policies that restrict third-party use of materials prepared by educators. It is your sole responsibility to be aware of and to abide by any such laws or policies that may apply to you. You may access materials solely for your information and your non-commercial, personal use and as intended through the normal functionality of the site and service..
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a comment.
        /// </summary>
        public static string CreateComment {
            get {
                return ResourceManager.GetString("CreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag an item.
        /// </summary>
        public static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string FlagItemPlaceHolder {
            get {
                return ResourceManager.GetString("FlagItemPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoyed this document? give it a like:.
        /// </summary>
        public static string LikeToasterText {
            get {
                return ResourceManager.GetString("LikeToasterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may take several minutes.
        /// </summary>
        public static string MayTake {
            get {
                return ResourceManager.GetString("MayTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string NewComment {
            get {
                return ResourceManager.GetString("NewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string NewReply {
            get {
                return ResourceManager.GetString("NewReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the.
        /// </summary>
        public static string PleaseUseThe {
            get {
                return ResourceManager.GetString("PleaseUseThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option to view..
        /// </summary>
        public static string PreviewFailed2 {
            get {
                return ResourceManager.GetString("PreviewFailed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preview is unavailable for this file type.
        /// </summary>
        public static string PreviewNotAvailable {
            get {
                return ResourceManager.GetString("PreviewNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing new media file.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report abuse.
        /// </summary>
        public static string ReportAbuse {
            get {
                return ResourceManager.GetString("ReportAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the raw text of the file.
        /// </summary>
        public static string ShowRawText {
            get {
                return ResourceManager.GetString("ShowRawText", resourceCulture);
            }
        }
    }
}
